### ISSUE TITLE
Project Progress Tracker Project

### ISSUE THREAD

**Issue by pramit-marattha** [pramit-marattha/Fullstack-projects-frontend-with-react-and-backend-with-various-stacks#24]
## Project Progress Tracker Project 

- [x] Setup Server
  - [x] Install Dependencies
  - [x] Setup Express App
- [x] Model DB
     - [x] Schema setup
        - [x]  ProjectSchema
        - [x] UserSchema 
  - [x] Setup Mongoose Model(s)
- [x] POST /logs
  - Create a new log entry
- [x] GET / logs
  - [x] Listing all log entries
- [x] Setting up react as a client
- [x] Create react Form to add a new entry(projects as well as users)
